set_property SRC_FILE_INFO {cfile:D:/PROJECT_RISCV_ASCON/fpga/riscv/riscv.srcs/constrs_1/new/riscv_constaint.xdc rfile:../../../riscv.srcs/constrs_1/new/riscv_constaint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { sys_clk }];
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { sys_rst_n }];
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { leds[0] }];
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { leds[1] }];
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { leds[2] }];
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { leds[3] }];
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports { uart_tx }];
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports { uart_rx }];
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/regwrite_retire_reg}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/regwrite_retire_fwd_reg}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/forward_a_reg[*]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/forward_b_reg[*]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/stall_any}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/mem_wb_reg/rd_out_reg[*]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/stall_any_ifid}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/stall_any_idex}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/mem_wb_reg/regwrite_out_reg}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/ex_mem_reg/rd_out_reg[*]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/rd_mem_fwd[*]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4 [get_nets {u_cpu/forward_a_ce[*]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4 [get_nets {u_cpu/forward_b_ce[*]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8 [get_nets {u_cpu/ex_mem_reg/regwrite_out_reg}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4 [get_nets {u_cpu/pc_src_ex_r}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4 [get_nets {u_cpu/target_pc_ex_r[*]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4 [get_nets {u_cpu/ifu_pc_src}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/regwrite_mem_fwd}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/regwrite_mem_mul}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/regwrite_mem_pip}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4  [get_nets {u_cpu/ex_mem_reg/regwrite_out_reg}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4  [get_nets {u_cpu/mul_operand_a[*]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 4  [get_nets {u_cpu/mul_operand_b[*]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/alu_in1_forwarded[*]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 16 [get_nets {u_cpu/alu_in2_pre_mux[*]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/fwd_a_mem}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/fwd_b_mem}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/fwd_a_wb}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 8  [get_nets {u_cpu/fwd_b_wb}]
