set_property SRC_FILE_INFO {cfile:D:/PROJECT_RISCV_ASCON/fpga/ascon/ascon.srcs/constrs_1/new/ascon_constraints.xdc rfile:../../../ascon.srcs/constrs_1/new/ascon_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16  IOSTANDARD LVCMOS33 } [get_ports { clk }]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19  IOSTANDARD LVCMOS33 } [get_ports { rst_n }]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14  IOSTANDARD LVCMOS33 } [get_ports { o_tag_valid }]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14  IOSTANDARD LVCMOS33 } [get_ports { o_busy      }]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N16  IOSTANDARD LVCMOS33 } [get_ports { irq         }]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -to [get_ports { o_tag_valid o_busy irq }]
